export interface Env {
  AI: Ai;
  SAFETY_DB: D1Database;
  PHOTOS: R2Bucket;
  VECTORIZE: VectorizeIndex;
  ASSETS: Fetcher;
  VECTORIZE_SEED_KEY?: string;
}

const MODEL = "@cf/meta/llama-3.2-11b-vision-instruct";
const EMBEDDING_MODEL = "@cf/baai/bge-base-en-v1.5";
const VECTOR_MATCH_THRESHOLD = 0.45;
const MAX_IMAGE_SIZE = 12 * 1024 * 1024;
const MAX_FINDINGS = 8;
type Status = "PASS" | "FAIL" | "CHECK_REQUIRED";
type Risk = "LOW" | "MEDIUM" | "HIGH";

interface SafetyCheck { id:string; category:string; check_question:string; guidance:string; source_title:string; source_url:string; keywords:string; }
interface Finding { category:string; title:string; observation:string; status:Status; risk_level:Risk; confidence:number; check_id:string|null; source_title:string|null; source_url:string|null; vector_score?:number|null; }
interface PhotoInput { bytes:ArrayBuffer; contentType:string; fileName:string; }
interface EmbeddingResponse { shape?:number[]; data:number[][]; pooling?:string; }

function jsonResponse(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type, X-Vectorize-Seed-Key"}})}
function textResponse(text:string,status=200){return new Response(text,{status,headers:{"Content-Type":"text/plain; charset=utf-8","Access-Control-Allow-Origin":"*"}})}
function uuid(){return crypto.randomUUID()}
function nowISO(){return new Date().toISOString()}
function clean(v:unknown,max=2000){return v==null?"":String(v).replace(/\u0000/g,"").trim().substring(0,max)}
function cleanMarkdown(v:unknown,max=2000){return clean(v,max).replace(/\*\*/g,"").replace(/__/g,"").replace(/^#+\s*/g,"").replace(/^[-*•]\s*/g,"").trim()}
function inspectionNumber(){const d=new Date();return `SI-${d.getUTCFullYear()}${String(d.getUTCMonth()+1).padStart(2,"0")}${String(d.getUTCDate()).padStart(2,"0")}-${uuid().replace(/-/g,"").substring(0,6).toUpperCase()}`}
function normalizeContentType(v:unknown){const t=String(v||"").toLowerCase().split(";")[0].trim();return ["image/png","image/webp","image/gif","image/heic","image/heif"].includes(t)?t:"image/jpeg"}
function extension(t:string){return ({"image/png":"png","image/webp":"webp","image/gif":"gif","image/heic":"heic","image/heif":"heif"} as Record<string,string>)[t]||"jpg"}
function safeFileName(v:string){const r=v.replace(/[^a-zA-Z0-9._-]/g,"_").substring(0,150);return r||"inspection-photo.jpg"}
function arrayBufferToBase64(b:ArrayBuffer){const a=new Uint8Array(b);let s="";for(let i=0;i<a.length;i+=0x8000)s+=String.fromCharCode(...a.subarray(i,Math.min(i+0x8000,a.length)));return btoa(s)}
function imageDataUrl(b:ArrayBuffer,t:string){return `data:${t};base64,${arrayBufferToBase64(b)}`}

async function parseRequest(request:Request){
  const ct=request.headers.get("content-type")||"";
  if(ct.toLowerCase().includes("multipart/form-data")){
    const form=await request.formData();let file:File|null=null;
    for(const n of ["image","photo","file","photoFile"]){const v=form.get(n);if(v instanceof File){file=v;break}}
    if(!file)for(const [,v] of form.entries())if(v instanceof File){file=v;break}
    if(!file)throw new Error("No image file was uploaded.");
    const bytes=await file.arrayBuffer();if(!bytes.byteLength)throw new Error("The uploaded image is empty.");if(bytes.byteLength>MAX_IMAGE_SIZE)throw new Error("The uploaded image is larger than 12 MB.");
    return {photo:{bytes,contentType:normalizeContentType(file.type),fileName:safeFileName(file.name||"inspection-photo.jpg")},location:clean(form.get("location"),200)||"Unspecified",inspector:clean(form.get("inspector"),200)||"Unspecified"};
  }
  let body:any;try{body=await request.json()}catch{throw new Error("Request body is not valid JSON.")}
  let base64=body?.image||body?.imageBase64||body?.photo;if(typeof base64!=="string"||!base64.trim())throw new Error("No image was supplied.");base64=base64.trim();let type=normalizeContentType(body?.mimeType||body?.contentType||"image/jpeg");
  const m=base64.match(/^data:(image\/[^;]+);base64,(.+)$/s);if(m){type=normalizeContentType(m[1]);base64=m[2]}
  let binary:string;try{binary=atob(base64)}catch{throw new Error("Image data is not valid base64.")}
  const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);if(!bytes.byteLength)throw new Error("The image is empty.");if(bytes.byteLength>MAX_IMAGE_SIZE)throw new Error("The image is larger than 12 MB.");
  return {photo:{bytes:bytes.buffer,contentType:type,fileName:safeFileName(body?.fileName||`inspection.${extension(type)}`)},location:clean(body?.location,200)||"Unspecified",inspector:clean(body?.inspector,200)||"Unspecified"};
}

const TABLES=["inspections","inspection_photos","inspection_items","safety_checks","corrective_actions"];
async function columns(db:D1Database,table:string){if(!TABLES.includes(table))throw new Error(`Invalid table: ${table}`);const r=await db.prepare(`PRAGMA table_info("${table}")`).all<{name:string}>();return new Set((r.results||[]).map(x=>x.name))}
function insertSQL(table:string,cols:Set<string>,values:Record<string,unknown>){if(!TABLES.includes(table))throw new Error(`Invalid table: ${table}`);const e=Object.entries(values).filter(([c])=>cols.has(c));if(!e.length)throw new Error(`No matching columns found in ${table}.`);return {sql:`INSERT INTO "${table}" (${e.map(([c])=>`"${c}"`).join(",")}) VALUES (${e.map(()=>"?").join(",")})`,params:e.map(([,v])=>v)}}

async function loadSafetyChecks(env:Env):Promise<SafetyCheck[]>{const c=await columns(env.SAFETY_DB,"safety_checks");const req=["id","category","check_question","guidance","source_title","source_url","keywords"];const miss=req.filter(x=>!c.has(x));if(miss.length)throw new Error(`safety_checks is missing columns: ${miss.join(", ")}`);const active=c.has("active")?"WHERE active = 1":"";const r=await env.SAFETY_DB.prepare(`SELECT id,category,check_question,guidance,source_title,source_url,keywords FROM safety_checks ${active} ORDER BY category,id LIMIT 40`).all<SafetyCheck>();return r.results||[]}

function buildPrompt(checks:SafetyCheck[]){const list=checks.map(c=>`CHECK ID: ${c.id}\nCATEGORY: ${c.category}\nQUESTION: ${clean(c.check_question,350)}\nGUIDANCE: ${clean(c.guidance,500)}\nKEYWORDS: ${clean(c.keywords,250)}\nSOURCE: ${clean(c.source_title,250)}\nURL: ${clean(c.source_url,500)}`).join("\n\n");return `You are a careful workplace safety inspection assistant for a Singapore shipping/container depot.\n\nAnalyse ONLY what is visibly supported by the photograph. Do not invent hazards. Do not assume every safety category applies. Only assess a category when there is visible evidence relevant to that category. If a category is not visibly relevant, OMIT it completely.\n\nDo NOT create findings such as No visible lifting operation, No visible work at height, No visible electrical equipment, No visible fire hazards, or No visible storage. These are NOT findings and must be omitted.\n\nPASS means the visible condition appears satisfactory. FAIL means a visible unsafe condition is identified. CHECK_REQUIRED means a relevant safety condition is visible but the photograph is insufficient to determine whether it is safe.\n\nRISK: LOW=satisfactory/minor concern, MEDIUM=potential concern, HIGH=serious visible concern. Confidence must be 0 to 1.\n\nReturn only relevant visible findings using exactly:\n**PPE**\n* **Title:** Visible PPE appears appropriate\n* **Observation:** The worker is visibly wearing a hard hat and high-visibility vest.\n* **Status:** PASS\n* **Risk:** LOW\n* **Confidence:** 0.88\n* **Check ID:** ppe-001\n\nAVAILABLE WSH CHECKS:\n${list}`}

async function runAI(env:Env,image:ArrayBuffer,type:string,checks:SafetyCheck[]){let r:any;try{r=await env.AI.run(MODEL,{messages:[{role:"system",content:"You are a careful Singapore workplace safety visual inspection assistant. Only report visible evidence."},{role:"user",content:buildPrompt(checks)}],image:imageDataUrl(image,type),max_tokens:900,temperature:0.05,top_p:0.8} as any)}catch(e){throw new Error(`Workers AI request failed: ${e instanceof Error?e.message:String(e)}`)}const raw=typeof r==="string"?r:typeof r?.response==="string"?r.response:typeof r?.result==="string"?r.result:"";if(!raw.trim())throw new Error(`Workers AI returned no text. Response: ${JSON.stringify(r).substring(0,3000)}`);return {raw:raw.trim(),result:r}}
function confidence(v:string){const m=v?.match(/(\d+(?:\.\d+)?)/);if(!m)return .6;let n=Number(m[1]);if(n>1)n/=100;return Math.round(Math.max(0,Math.min(1,n))*100)/100}
function status(v:string,o:string):Status{const t=cleanMarkdown(v).toUpperCase();if(t.includes("FAIL"))return"FAIL";if(t.includes("PASS"))return"PASS";if(t.includes("CHECK"))return"CHECK_REQUIRED";return ["unsafe","hazard","spill","obstructed","blocked","missing","damaged","exposed","unguarded"].some(x=>o.toLowerCase().includes(x))?"FAIL":"CHECK_REQUIRED"}
function risk(v:string,s:Status):Risk{const t=cleanMarkdown(v).toUpperCase();if(t.includes("HIGH"))return"HIGH";if(t.includes("MEDIUM"))return"MEDIUM";if(t.includes("LOW"))return"LOW";return s==="FAIL"?"HIGH":s==="PASS"?"LOW":"MEDIUM"}
function negative(c:string,t:string,o:string){const x=`${c} ${t} ${o}`.toLowerCase().replace(/\s+/g," ");return ["no visible","not visible","there is no visible","no evidence","cannot be determined","not observed","not apparent","no work at height","no lifting operation","no electrical equipment","no fire hazards","no storage hazards"].some(p=>x.includes(p))}
function category(v:string){const x=cleanMarkdown(v,100).toLowerCase();if(x==="ppe"||x.includes("personal protective"))return"PPE";if(x.includes("housekeeping"))return"Housekeeping";if(x.includes("vehicular")||x.includes("vehicle")||x.includes("traffic"))return"Vehicular Safety";if(x.includes("work at height")||x.includes("working at height"))return"Work at Height";if(x.includes("lifting"))return"Lifting";if(x.includes("electrical"))return"Electrical Safety";if(x.includes("fire"))return"Fire Safety";if(x.includes("storage"))return"Storage";return cleanMarkdown(v,100)}

function parseAI(raw:string){const text=raw.replace(/\r/g,"").trim();const out:any[]=[];const re=/(?:^|\n)\s*\*\*([^*\n]+)\*\*\s*(?=\n)/g;const hs:any[]=[];let m:RegExpExecArray|null;while((m=re.exec(text))!==null){const c=cleanMarkdown(m[1]);if(c&&!['Title','Observation','Status','Risk','Confidence','Check ID','Category'].includes(c))hs.push({index:m.index,category:c})}for(let i=0;i<hs.length&&out.length<MAX_FINDINGS;i++){const body=text.substring(hs[i].index,i+1<hs.length?hs[i+1].index:text.length),c=category(hs[i].category);const tm=body.match(/(?:^|\n)\s*(?:\*\s*)?\*\*Title:\*\*\s*(.+?)(?=\n|$)/i),om=body.match(/(?:^|\n)\s*(?:\*\s*)?\*\*Observation:\*\*\s*(.+?)(?=\n|$)/i),sm=body.match(/(?:^|\n)\s*(?:\*\s*)?\*\*Status:\*\*\s*(PASS|FAIL|CHECK_REQUIRED)/i),rm=body.match(/(?:^|\n)\s*(?:\*\s*)?\*\*Risk:\*\*\s*(LOW|MEDIUM|HIGH)/i),cm=body.match(/(?:^|\n)\s*(?:\*\s*)?\*\*Confidence:\*\*\s*([0-9.]+)/i),im=body.match(/(?:^|\n)\s*(?:\*\s*)?\*\*Check ID:\*\*\s*([^\s\n]+)/i);const t=cleanMarkdown(tm?.[1]||`${c} observation`),o=cleanMarkdown(om?.[1]||"");if(!o||negative(c,t,o))continue;const s=status(sm?.[1]||"",o);out.push({category:c,title:t,observation:o,status:s,risk:risk(rm?.[1]||"",s),confidence:confidence(cm?.[1]||""),checkId:cleanMarkdown(im?.[1]||"")})}return out.length?out:legacy(raw)}
function legacy(raw:string){const out:any[]=[];for(const b of raw.split(/(?=\*\*Category:\*\*)/i)){const cm=b.match(/\*\*Category:\*\*\s*(.+?)(?=\n|$)/i);if(!cm)continue;const c=category(cm[1]),tm=b.match(/\*\*Title:\*\*\s*(.+?)(?=\n|$)/i),om=b.match(/\*\*Observation:\*\*\s*(.+?)(?=\n|$)/i),sm=b.match(/\*\*Status:\*\*\s*(PASS|FAIL|CHECK_REQUIRED)/i),rm=b.match(/\*\*Risk:\*\*\s*(LOW|MEDIUM|HIGH)/i),cmf=b.match(/\*\*Confidence:\*\*\s*([0-9.]+)/i),im=b.match(/\*\*Check ID:\*\*\s*([^\s\n]+)/i);const t=cleanMarkdown(tm?.[1]||`${c} observation`),o=cleanMarkdown(om?.[1]||"");if(!o||negative(c,t,o))continue;const s=status(sm?.[1]||"",o);out.push({category:c,title:t,observation:o,status:s,risk:risk(rm?.[1]||"",s),confidence:confidence(cmf?.[1]||""),checkId:cleanMarkdown(im?.[1]||"")});if(out.length>=MAX_FINDINGS)break}return out}

async function embed(env:Env,text:string){let r:EmbeddingResponse;try{r=await env.AI.run(EMBEDDING_MODEL,{text:[text]}) as EmbeddingResponse}catch(e){throw new Error(`Embedding generation failed: ${e instanceof Error?e.message:String(e)}`)}const v=r?.data?.[0];if(!Array.isArray(v)||v.length!==768)throw new Error(`Invalid embedding returned. Expected 768 dimensions, got ${Array.isArray(v)?v.length:0}.`);return v}
async function vectorSearch(env:Env,f:{category:string;title:string;observation:string}){const v=await embed(env,`Safety category: ${f.category}. Finding: ${f.title}. Observation: ${f.observation}`);let r:any;try{r=await env.VECTORIZE.query(v,{topK:3,returnMetadata:"none"} as any)}catch(e){throw new Error(`Vectorize query failed: ${e instanceof Error?e.message:String(e)}`)}for(const x of Array.isArray(r?.matches)?r.matches:[]){const score=Number(x?.score),id=clean(x?.id,200);if(!id||!Number.isFinite(score)||score<VECTOR_MATCH_THRESHOLD)continue;const c=await env.SAFETY_DB.prepare(`SELECT id,category,check_question,guidance,source_title,source_url,keywords FROM safety_checks WHERE id=? LIMIT 1`).bind(id).first<SafetyCheck>();if(c)return{check:c,score:Math.round(score*1000)/1000}}const best=Number(r?.matches?.[0]?.score);return{check:null,score:Number.isFinite(best)?Math.round(best*1000)/1000:null}}
async function findCheck(env:Env,f:{category:string;title:string;observation:string;checkId:string}){try{const v=await vectorSearch(env,f);if(v.check)return{check:v.check,vectorScore:v.score,method:"vectorize"};if(f.checkId){const c=await env.SAFETY_DB.prepare(`SELECT id,category,check_question,guidance,source_title,source_url,keywords FROM safety_checks WHERE id=? LIMIT 1`).bind(f.checkId).first<SafetyCheck>();if(c)return{check:c,vectorScore:v.score,method:"ai_check_id"}}return{check:null,vectorScore:v.score,method:"none"}}catch{if(f.checkId){try{const c=await env.SAFETY_DB.prepare(`SELECT id,category,check_question,guidance,source_title,source_url,keywords FROM safety_checks WHERE id=? LIMIT 1`).bind(f.checkId).first<SafetyCheck>();if(c)return{check:c,vectorScore:null,method:"ai_check_id"}}catch{}}return{check:null,vectorScore:null,method:"none"}}}
async function normalizeFindings(env:Env,parsed:any[]):Promise<Finding[]>{const out:Finding[]=[];const seen=new Set<string>();for(const x of parsed){const c=category(x.category),t=cleanMarkdown(x.title,250),o=cleanMarkdown(x.observation,1200);if(!c||!o||negative(c,t,o))continue;const key=`${c}|${t}|${o}`.toLowerCase().replace(/\s+/g," ");if(seen.has(key))continue;seen.add(key);const m=await findCheck(env,{category:c,title:t,observation:o,checkId:x.checkId});out.push({category:c,title:t,observation:o,status:x.status,risk_level:x.risk,confidence:Math.round(Math.max(0,Math.min(1,Number(x.confidence)||.6))*100)/100,check_id:m.check?.id||null,source_title:m.check?.source_title||null,source_url:m.check?.source_url||null,vector_score:m.vectorScore});if(out.length>=MAX_FINDINGS)break}return out}
function overall(fs:Finding[]):"PASS"|"ATTENTION"|"CHECK_REQUIRED"{if(!fs.length)return"CHECK_REQUIRED";if(fs.some(f=>f.status==="FAIL"))return"ATTENTION";if(fs.some(f=>f.status==="CHECK_REQUIRED"))return"CHECK_REQUIRED";return"PASS"}
function summary(fs:Finding[]){if(!fs.length)return"No visible safety conditions were identified from the photograph.";const p=fs.filter(f=>f.status==="PASS").length,f=fs.filter(f=>f.status==="FAIL").length,c=fs.filter(f=>f.status==="CHECK_REQUIRED").length;if(f)return`${f} visible safety finding(s) require corrective attention. ${c} item(s) require verification and ${p} item(s) passed.`;if(c)return`${c} visible safety item(s) require verification. ${p} item(s) passed.`;return`${p} visible safety item(s) were assessed as PASS.`}

async function saveInspection(env:Env,id:string,no:string,location:string,inspector:string,created:string){const c=await columns(env.SAFETY_DB,"inspections"),q=insertSQL("inspections",c,{id,inspection_no:no,location:location||null,inspector:inspector||null,created_at:created,overall_result:"CHECK_REQUIRED"});await env.SAFETY_DB.prepare(q.sql).bind(...q.params).run()}
async function savePhoto(env:Env,pid:string,iid:string,key:string,name:string,type:string,created:string){const c=await columns(env.SAFETY_DB,"inspection_photos");if(!c.has("object_key"))throw new Error("inspection_photos.object_key column does not exist.");const q=insertSQL("inspection_photos",c,{id:pid,inspection_id:iid,object_key:key,file_name:name,content_type:type,created_at:created});await env.SAFETY_DB.prepare(q.sql).bind(...q.params).run()}
async function saveItems(env:Env,iid:string,pid:string,fs:Finding[]){if(!fs.length)return;const c=await columns(env.SAFETY_DB,"inspection_items");await env.SAFETY_DB.batch(fs.map(f=>{const q=insertSQL("inspection_items",c,{id:uuid(),inspection_id:iid,photo_id:pid,category:f.category,title:f.title,observation:f.observation,status:f.status,risk_level:f.risk_level,confidence:f.confidence,check_id:f.check_id,source_title:f.source_title,source_url:f.source_url,vector_score:f.vector_score,created_at:nowISO()});return env.SAFETY_DB.prepare(q.sql).bind(...q.params)}))}
async function updateInspection(env:Env,id:string,result:"PASS"|"ATTENTION"|"CHECK_REQUIRED"){const c=await columns(env.SAFETY_DB,"inspections");if(c.has("overall_result"))await env.SAFETY_DB.prepare("UPDATE inspections SET overall_result=? WHERE id=?").bind(result,id).run()}
async function r2put(env:Env,key:string,p:PhotoInput,meta:any){await env.PHOTOS.put(key,p.bytes,{httpMetadata:{contentType:p.contentType,contentDisposition:`inline; filename="${p.fileName}"`},customMetadata:meta})}

async function analyze(request:Request,env:Env){let stage="starting",iid="",pid="",key="",uploaded=false;try{stage="parse image";const input=await parseRequest(request),p=input.photo;stage="create IDs";iid=uuid();pid=uuid();const no=inspectionNumber(),created=nowISO();key=`inspections/${iid}/${pid}.${extension(p.contentType)}`;stage="D1 create inspection";await saveInspection(env,iid,no,input.location,input.inspector,created);stage="R2 upload";await r2put(env,key,p,{inspectionId:iid,photoId:pid,inspectionNo:no});uploaded=true;stage="D1 save inspection photo";await savePhoto(env,pid,iid,key,p.fileName,p.contentType,created);stage="load safety checks";const checks=await loadSafetyChecks(env);stage="Workers AI Vision";const ai=await runAI(env,p.bytes,p.contentType,checks);stage="parse AI response";const parsed=parseAI(ai.raw);stage="Vectorize semantic matching";const fs=await normalizeFindings(env,parsed);stage="D1 save inspection items";await saveItems(env,iid,pid,fs);stage="update result";const result=overall(fs);await updateInspection(env,iid,result);return jsonResponse({ok:true,inspection:{id:iid,inspection_no:no,location:input.location,inspector:input.inspector,overall_result:result,created_at:created},photo:{id:pid,object_key:key,file_name:p.fileName,content_type:p.contentType},ai:{model:MODEL,embedding_model:EMBEDDING_MODEL,response_length:ai.raw.length,response_preview:ai.raw.substring(0,3000)},vectorize:{enabled:true,index:"safety-checks",threshold:VECTOR_MATCH_THRESHOLD,matches_used:fs.filter(f=>f.vector_score!=null).length},summary:summary(fs),findings:fs,counts:{total:fs.length,pass:fs.filter(f=>f.status==="PASS").length,fail:fs.filter(f=>f.status==="FAIL").length,check_required:fs.filter(f=>f.status==="CHECK_REQUIRED").length}})}catch(e){const detail=e instanceof Error?e.message:String(e);if(uploaded&&key)try{await env.PHOTOS.delete(key)}catch{}if(iid)try{await updateInspection(env,iid,"CHECK_REQUIRED")}catch{}return jsonResponse({ok:false,error:`AI analysis failed.\nStage: ${stage}\nDetail: ${detail}`,stage,detail,inspectionId:iid||null,photoId:pid||null,objectKey:key||null},500)}}

async function seedVectorize(request:Request,env:Env){const secret=clean(env.VECTORIZE_SEED_KEY,500);if(!secret)return jsonResponse({ok:false,error:"VECTORIZE_SEED_KEY is not configured. Create this Worker secret before running the seed operation."},503);if(clean(request.headers.get("X-Vectorize-Seed-Key"),500)!==secret)return jsonResponse({ok:false,error:"Invalid Vectorize seed key."},401);try{const checks=await loadSafetyChecks(env);const texts=checks.map(c=>`Safety category: ${c.category}. Check: ${c.check_question}. Guidance: ${c.guidance}. Keywords: ${c.keywords}.`);const r=await env.AI.run(EMBEDDING_MODEL,{text:texts}) as EmbeddingResponse;if(!r?.data||r.data.length!==checks.length)throw new Error(`Embedding count mismatch. Expected ${checks.length}, got ${r?.data?.length||0}.`);const vectors:VectorizeVector[]=checks.map((c,i)=>({id:c.id,values:r.data[i],metadata:{category:c.category,source_title:c.source_title}}));const mutation=await env.VECTORIZE.upsert(vectors);return jsonResponse({ok:true,message:"Safety checks successfully indexed into Vectorize.",index:"safety-checks",embedding_model:EMBEDDING_MODEL,dimensions:768,indexed:checks.length,ids:checks.map(c=>c.id),mutation})}catch(e){return jsonResponse({ok:false,error:e instanceof Error?e.message:String(e)},500)}}
async function vectorTest(request:Request,env:Env){try{const b=await request.json().catch(()=>({}));const q=clean(b?.query,1000);if(!q)return jsonResponse({ok:false,error:"Missing query."},400);const v=await embed(env,q);const r=await env.VECTORIZE.query(v,{topK:5,returnMetadata:"all"} as any);return jsonResponse({ok:true,query:q,embedding_model:EMBEDDING_MODEL,dimensions:v.length,threshold:VECTOR_MATCH_THRESHOLD,matches:r?.matches||[]})}catch(e){return jsonResponse({ok:false,error:e instanceof Error?e.message:String(e)},500)}}

async function health(env:Env){let database=false,safetyChecks=false,r2=false,vectorize=false;try{await env.SAFETY_DB.prepare("SELECT 1 AS ok").first();database=true}catch{}try{await loadSafetyChecks(env);safetyChecks=true}catch{}try{r2=!!env.PHOTOS}catch{}try{vectorize=!!env.VECTORIZE}catch{}return jsonResponse({ok:database&&safetyChecks&&r2&&vectorize,worker:"depot-safety",model:MODEL,embedding_model:EMBEDDING_MODEL,database,safety_checks:safetyChecks,r2,vectorize,vectorize_index:"safety-checks",vectorize_dimensions:768,vector_match_threshold:VECTOR_MATCH_THRESHOLD,timestamp:nowISO()})}
async function inspections(env:Env){const r=await env.SAFETY_DB.prepare("SELECT * FROM inspections ORDER BY created_at DESC LIMIT 30").all();return jsonResponse({ok:true,inspections:r.results||[]})}
async function inspection(env:Env,id:string){const i=await env.SAFETY_DB.prepare("SELECT * FROM inspections WHERE id=? LIMIT 1").bind(id).first();if(!i)return jsonResponse({ok:false,error:"Inspection not found."},404);const p=await env.SAFETY_DB.prepare("SELECT * FROM inspection_photos WHERE inspection_id=? ORDER BY created_at").bind(id).all();const f=await env.SAFETY_DB.prepare("SELECT ii.*,sc.check_question,sc.guidance FROM inspection_items ii LEFT JOIN safety_checks sc ON sc.id=ii.check_id WHERE ii.inspection_id=? ORDER BY ii.created_at").bind(id).all();return jsonResponse({ok:true,inspection:i,photos:p.results||[],findings:f.results||[]})}
async function photo(env:Env,key:string){const o=await env.PHOTOS.get(key);if(!o)return textResponse("Photo not found.",404);const h=new Headers();o.writeHttpMetadata(h);h.set("ETag",o.httpEtag);h.set("Cache-Control","private, max-age=3600");return new Response(o.body,{headers:h})}

async function api(request:Request,env:Env,url:URL){const p=url.pathname;if(request.method==="GET"&&p==="/api/health")return health(env);if(request.method==="POST"&&(p==="/api/analyze"||p==="/api/analysis"))return analyze(request,env);if(request.method==="GET"&&p==="/api/inspections")return inspections(env);if(request.method==="GET"&&p.startsWith("/api/inspection/"))return inspection(env,decodeURIComponent(p.substring(17)));if(request.method==="GET"&&p==="/api/safety-checks")return jsonResponse({ok:true,count:(await loadSafetyChecks(env)).length,checks:await loadSafetyChecks(env)});if(request.method==="GET"&&p==="/api/photo"){const k=url.searchParams.get("key");return k?photo(env,k):textResponse("Missing photo key.",400)}if(request.method==="POST"&&p==="/api/vectorize/seed")return seedVectorize(request,env);if(request.method==="POST"&&p==="/api/vectorize/test")return vectorTest(request,env);return jsonResponse({ok:false,error:"API endpoint not found.",path:p},404)}

export default {async fetch(request:Request,env:Env){try{if(request.method==="OPTIONS")return new Response(null,{status:204,headers:{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type, X-Vectorize-Seed-Key"}});const url=new URL(request.url);if(url.pathname.startsWith("/api/"))return api(request,env,url);try{const asset=await env.ASSETS.fetch(request);if(asset.status!==404)return asset}catch{}return new Response("Depot Safety AI is running.",{status:200,headers:{"Content-Type":"text/plain; charset=utf-8"}})}catch(e){return jsonResponse({ok:false,error:e instanceof Error?e.message:String(e)},500)}}} satisfies ExportedHandler<Env>;
